#!/bin/sh

if [ "$#" -ne 3 ]; then
    echo ""
    echo "Usage: ./projectrunscript <suite> <benchmark> <repl_policy>"
    echo "    (suite) benchmarks: "
    echo "      -- (SPEC) bzip2, gcc, mcf, hmmer, xalancbmk, sjeng, libquantum, milc, cactusADM, leslie3d, namd, calculix, soplex, and lbm."
    echo "      -- (PARSEC) blackscholes, bodytrack, fluidanimate, streamcluster, swaptions, canneal, and x264."
    echo "    repl_policy: LRU LFU SRRIP CARE Rand"
else
    suite=$1
    bench=$2
    repl_pol=$3

    # your simulation results will be saved to outputs/project/$repl_pol/$bench/
    if [ "$suite" = "SPEC" ]; then
        mkdir -p outputs/project/$repl_pol/${bench}
        echo "./build/opt/zsim configs/project/$repl_pol/${bench}.cfg > outputs/project/$repl_pol/${bench}/${bench}.log 2>&1 &"
        ./build/opt/zsim configs/project/$repl_pol/${bench}.cfg > outputs/project/$repl_pol/${bench}/${bench}.log 2>&1 &
    elif [ "$suite" = "PARSEC" ]; then
        mkdir -p outputs/project/$repl_pol/${bench}_8c_simlarge
        echo "./build/opt/zsim configs/project/$repl_pol/${bench}_8c_simlarge.cfg > outputs/project/$repl_pol/${bench}_8c_simlarge/${bench}.log 2>&1 &"
        ./build/opt/zsim configs/project/$repl_pol/${bench}_8c_simlarge.cfg > outputs/project/$repl_pol/${bench}_8c_simlarge/${bench}.log 2>&1 &
    else
        echo "No such benchmark suite, please specify SPEC or PARSEC"
    fi
fi
